# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Optishell < Formula
  desc ""
  homepage "https://github.com/Optibus/homebrew-tap"
  version "0.0.1-rc3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Optibus/optishell/releases/download/v0.0.1-rc3/optishell_Darwin_arm64.tar.gz", using: PrivateGithubDownloadStrategy
      sha256 "529793b7fbaaad2918de8d8a549c88a648eb342faee89c5f70e124aca77caa99"

      def install
        bin.install "optishell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Optibus/optishell/releases/download/v0.0.1-rc3/optishell_Linux_x86_64.tar.gz", using: PrivateGithubDownloadStrategy
        sha256 "166948ad0d4178cfb993588605c6b42f7cac700e4fcbbec63efabb26beb2d6da"

        def install
          bin.install "optishell"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Optibus/optishell/releases/download/v0.0.1-rc3/optishell_Linux_arm64.tar.gz", using: PrivateGithubDownloadStrategy
        sha256 "6bf196f0450ff96504cbbe1c0281c649ab0371022e39652e4cc20765717a41dc"

        def install
          bin.install "optishell"
        end
      end
    end
  end
end
