# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class Optishell < Formula
  desc ""
  homepage "https://github.com/Optibus/homebrew-tap"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Optibus/optishell/releases/download/v0.0.3/optishell_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7bab07a4df2c2d86d1c5c0e593afd7c3da32f0c89401b762d03d718ab82ebccd"

      def install
        bin.install "optishell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Optibus/optishell/releases/download/v0.0.3/optishell_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "714cdbc82e0a8686b6f102b136b53e1e24f6dbea0899d1d7a290472497982299"

        def install
          bin.install "optishell"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Optibus/optishell/releases/download/v0.0.3/optishell_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "03de646baf13fd3abfcc6d2831d897db3ef1f44b94af8d796ce1a985e2a6d6b4"

        def install
          bin.install "optishell"
        end
      end
    end
  end
end
